# Use a Shiny base image from Docker Hub
FROM rocker/shiny:4.3.0
LABEL Maintainer="Sarayut (Nine) Winuthayanon, https://www.linkedin.com/in/winuthayanons/"

# Install system dependencies
RUN apt-get update && \
    apt-get install -y libssl-dev libxml2-dev libcurl4-openssl-dev libbz2-dev liblzma-dev libpcre3-dev cmake

# Copy the app files into the Docker image
COPY functions/ /srv/shiny-server/functions/
COPY trans/ /srv/shiny-server/trans/
COPY uiTabs/ /srv/shiny-server/uiTabs/
COPY www/ /srv/shiny-server/www/
COPY app.R /srv/shiny-server/
COPY run.sh /usr/bin/run.sh

# Copy the custom run script into the Docker image
COPY run.sh /usr/bin/run.sh

# Set the executable permissions for the custom run script
RUN chmod +x /usr/bin/run.sh

# Upgrade R packages
RUN R -e "install.packages(c('shiny', 'shinythemes', 'stringi', 'DT', 'shinyBS', 'shinyjs', 'shinycssloaders', 'colourpicker', 'purrr', 'shinyFiles', 'UpSetR'), repos='https://cran.rstudio.com/', upgrade=TRUE)"
RUN R -e "install.packages(c('dplyr', 'ggplot2', 'plotly', 'kmer', 'factoextra', 'jsonlite', 'LaF'), repos='https://cran.rstudio.com/', upgrade=TRUE)"
RUN R -e "install.packages('BiocManager', repos='https://cran.rstudio.com/', upgrade=TRUE)"
# RUN R -e "BiocManager::install(c('Rhtslib', 'Rsamtools', 'GenomicAlignments', 'rtracklayer', 'BSgenome'), version = '3.13')"
RUN R -e "BiocManager::install(c('Rhtslib', 'Rsamtools', 'GenomicAlignments', 'rtracklayer', 'BSgenome'), upgrade=TRUE)"

# Install LaF package from GitHub
RUN R -e "install.packages('remotes', repos='https://cran.rstudio.com/', upgrade=TRUE)"
# RUN R -e "remotes::install_url('https://github.com/djvanderlaan/LaF/archive/refs/tags/v0.6.3.tar.gz', INSTALL_opts = '--no-multiarch')"

# Expose port 3838 for Shiny Server
EXPOSE 3838

# Set the command to start the Shiny app when the container is run
CMD ["/usr/bin/run.sh"]
